name: rasmus_fuel
channels:
  - conda-forge
dependencies:
  - python=3.9.6
  - myst-parser
  - nbsphinx
  - numpy=1.21.1
  - sphinx=4.1.2
  - sphinx-autosummary-accessors=0.2.1
  - sphinx_rtd_theme=0.5.2
  - pip=21.2.2
  - pip:
      - git+https://github.com/willirath/rasmus_fuel
